#!/usr/bin/php
<?php

// include command
require __DIR__.'/vendor/autoload.php';

// Create console application
$console = new Bright\Console\Command();

// register all commands
$console->registerCommand();

// Run it
$console->run();