#!/usr/bin/php
<?php

// include command
require __DIR__.'/vendor/autoload.php';

$command = $argv[1];

switch ($command) {
    case 'serve':
        Bright\Console\Command::serve((isset($argv[2])) ? $argv[2] : null);
        break;

    case 'list':
        Bright\Console\Command::listCommand();
        break;    
    
    default:
        Bright\Console\Command::commandNotFound($command);
        break;
}
?>